version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tmdb_teste
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmdb_teste
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
